language: python
python:
- '3.6'
install:
- pip3 install -r requirements.txt
script:
- pip3 install -r requirements_test.txt
- flake8 .
deploy:
  provider: heroku
  api_key:
    secure: UBXYrwTTxQLNWzttCHcTeULTqAs/AzaWi8EABlbrnCeYgwSjDaKDqk+75jvlTlkLn8Bcsb0oYfRlOyFpouI3r4ITj2F8/DaN3k00qGbuO7aTjutlhnBp4mfgPwtILqweVMU2rUTHBrEfAFvTuKq2tyCcXXmYnqlC/H3IwNra5vCdR28YgyPzpEsF1+lIGB/DVUeqGzNLd61u+qHOWlOPRvUCl7jQz2gL+rwpAEPEpNuCML+O829w/M5EI2BDprvKj39gaVCDV9/jNOhTyWuy7h7d+cFpb7qk6YuZ/1mMOq7Lb+Tjblrn4C7LGG8D+SvVrw8ZFRKAUt3c6iZZ1VchMH5gjAazR+AQqppHyyjsFXX9FCcFriCY+aP78qvaqaJjT0pKHOdGgoAAqt0gKZYLni78AE/L5B2KWKSncS9hsM4VEvdlrHTgkc+p08OgTd/Noe38YHYMOZazHHnv5CqKwDbIA+0A/exzyFkQOPkrtrj+7SqqLp2vSHPQ5AahE6zwFTopLtMZT6S5lIU5enEQMOdJkB6Rq4TMcibvZNW9iJy6I2+UvYtdb5YwiIP1PGaIJjp47h9bPsCXHMgvRcHhXGR0XAwXY+qO519eTG8Tcc7w42PUcKYe4A4xmG2AHZvfdK3jZAkHrcuLpOalgxcDHKGOOizCgGonmS6wRT1WvHY=
  app:
    master: govuk-notify-flask
  on:
    repo: LandRegistry/govuk-notify-flask
